# Site Settings
remote_theme: "mmistakes/minimal-mistakes@master"
minimal_mistakes_skin: "default"

# Basic Info
locale: "en-US"
title: "Croft"
title_separator: "-"
description: "Nothing lasts forever!"
url: "https://croft233.github.io"
baseurl: ""  # Leave empty if hosted at the repository root
words_per_minite: 200

# Build settings
plugins:
  - jekyll-include-cache

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Deployment
deploy:
  type: git
  repository: git@github.com:Croft233/magician233.github.io.git
  branch: main

